-- Migration: add Ledstjärnan logic reference tables
-- Generated by Codex on 2026-02-19

begin;

-- 1. Treatment levels
create table if not exists treatment_levels (
    id uuid primary key default gen_random_uuid(),
    code text not null unique,
    name text not null,
    description text,
    requires_baseline boolean not null default true,
    auto_assignment_logic jsonb,
    created_at timestamptz not null default now()
);

-- 2. Scoring dimensions
create table if not exists scoring_dimensions (
    id uuid primary key default gen_random_uuid(),
    code text not null unique,
    description text,
    scale_direction text not null check (scale_direction in ('NORMAL','INVERTED')),
    created_at timestamptz not null default now()
);

-- 3. Assessment domains
create table if not exists assessment_domains (
    id uuid primary key default gen_random_uuid(),
    dimension_id uuid not null references scoring_dimensions(id) on delete cascade,
    code text not null unique,
    label text not null,
    description text,
    life_area_order int,
    question_set_ref text,
    created_at timestamptz not null default now()
);

-- 4. Domain score slots (I / M / P etc)
create table if not exists domain_score_slots (
    id uuid primary key default gen_random_uuid(),
    domain_id uuid not null references assessment_domains(id) on delete cascade,
    slot_code text not null,
    label text not null,
    description text,
    actor text not null check (actor in ('CLIENT','STAFF','SYSTEM')),
    scale_min int not null default 1,
    scale_max int not null default 5,
    unique (domain_id, slot_code)
);

-- 5. Assessment steps (1–4 process guidance)
create table if not exists assessment_steps (
    id serial primary key,
    step_number int not null unique,
    title text not null,
    description text not null
);

-- 6. Trauma question catalog (events + symptom references)
create table if not exists trauma_questions (
    id serial primary key,
    code text not null unique,
    question_number int,
    label text not null,
    question_type text not null check (question_type in ('BOOLEAN','SCALE','TEXT')),
    group_code text not null,
    scale_min int,
    scale_max int,
    help_text text
);

-- 7. PTSD / trauma rule thresholds
create table if not exists trauma_rules (
    id serial primary key,
    rule_code text not null unique,
    description text not null,
    logic jsonb not null
);

-- 8. Guidebook entries for surfaced copy
create table if not exists guidebook_entries (
    id uuid primary key default gen_random_uuid(),
    slug text not null unique,
    category text,
    content_md text not null,
    created_at timestamptz not null default now()
);

commit;
